name: cd

on:
  push: 
    branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
          - name: Check out Code
            uses: actions/checkout@v4
            
          - name: Set Up Go Toolchain
            uses: actions/setup-go@v5
            with:
                go-version: "1.23.0"

          - name: Build Binary
            run: (./scripts/buildprod.sh)
